adapter_name_or_path: saves/LLaMA3-8B/lora/train_act_content1
cutoff_len: 1024
dataset: act_test_modified
dataset_dir: data
do_predict: true
finetuning_type: lora
flash_attn: auto
max_new_tokens: 512
max_samples: 750
model_name_or_path: /root/autodl-fs/llama3-8b/Meta-Llama-3-8B
output_dir: saves/LLaMA3-8B/lora/eval_act_content1
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
stage: sft
temperature: 0.5
template: llama3
top_p: 0.7
