eval.batch_size: 2
eval.cutoff_len: 1024
eval.dataset:
- env_test_modified
eval.dataset_dir: data
eval.max_new_tokens: 512
eval.max_samples: '600'
eval.output_dir: eval_env
eval.predict: true
eval.temperature: 0.5
eval.top_p: 0.7
top.booster: none
top.checkpoint_path:
- train_env
top.finetuning_type: lora
top.model_name: LLaMA3-8B
top.quantization_bit: none
top.rope_scaling: none
top.template: llama3
top.visual_inputs: false
